// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpxukefminceflddgxrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndweHVrZWZtaW5jZWZsZGRneHJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MDU4NjQsImV4cCI6MjA2ODA4MTg2NH0.wDr7Ivjakq_gjWpnKR96gRtjy_UgAWVP-HJkzc6lYpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});